### ISSUE TITLE
specify a provider to use

### ISSUE THREAD

**Issue by arasheedu** [chef/chef-provisioning-vagrant#17]
Any guidelines on how to go about using chef-provisioning-vagrant but at the same time specify a provider for vagrant to use ( other than virtual box ) ?

**Comment by pburkholder** [comment]
I could use this too. This fails for me:

```
with_driver 'vagrant:~/.vagrant.d/boxes' do

  options = {
    vagrant_options: { 
       'vm.box' => 'opscode-ubuntu-14.04',
       'vm.provider' => 'vmware_fusion'
    },
    convergence_options: context.convergence_options
  }


  machine context.node_name do
    machine_options(options)

    # This forces a chef run every time, which is sensible for `chef provision`
    # use cases.
    converge(true)
    action(context.action)
  end
end
```

throws: 

```
STDOUT:Bringing machine 'aar-staging-01' up with 'vmware_fusion' provider...

STDERR:There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The following settings shouldn't exist: provider
```

**Comment by scotthain** [comment]
I have a PR here that may be useful for this https://github.com/chef/chef-provisioning-vagrant/pull/22

**Comment by DarshanMurthy** [comment]
@pburkholde Even I am facing the similar issues. Since, I am using my own VM box so I have to customize the Vagrant file as well.

**Comment by tyler-ball** [comment]
I'm going to close this since we just merged https://github.com/chef/chef-provisioning-vagrant/pull/22
