### ISSUE TITLE
Chef Provisioning- Vagrant (Vagrant Config Issues)

### ISSUE THREAD

**Issue by DarshanMurthy** [chef/chef-provisioning-vagrant#21]
I have an issue in adding this line:

override.vm.synced_folder ".", "/vagrant", disabled: false

to my Vagrant file. Is there any way to use this library (https://github.com/chef/chef-provisioning-vagrant) and add the line.

Please, help.

**Comment by DarshanMurthy** [comment]
![screen shot 2015-07-01 at 2 19 49 pm](https://cloud.githubusercontent.com/assets/7928496/8465166/9e9969f6-1ffc-11e5-812d-6dd8c81956ad.png)
![screen shot 2015-07-01 at 2 22 04 pm](https://cloud.githubusercontent.com/assets/7928496/8465177/aa732f78-1ffc-11e5-8855-e4fe57592181.png)

**Comment by afiune** [comment]
@DarshanMurthy Sure you can... You could pass the following `machine_options`
```
{
  vagrant_options: {
    'vm.box' => 'sles11sp3',
    'vm.box_url' => 'http://jenkins-hzn.eng.vmware.com/tools/vagrant/sles11sp3.box',
    'vm.hostname' => 'default-sles11sp3.vagrantup.com'
  },
  vagrant_config: <<-END.gsub(/^ {4}/, '')
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.provider :vmware_fusion do |p|
    end
  END
}
```

**Comment by DarshanMurthy** [comment]
@afiune Thanks... Still it says no vms.
![screen shot 2015-07-02 at 8 38 03 am](https://cloud.githubusercontent.com/assets/7928496/8481002/ce774d3e-2095-11e5-948d-4e4948c9758d.png)

**Comment by afiune** [comment]
We need more information.. Could you share your cookbook? The `machine_options` must be run first and then all the `machine` resources. I do not see any resource..

**Comment by DarshanMurthy** [comment]
We are not using cookbooks as such... We are trying to run you examples (~/docs/examples)
Simple.rb and vagrant_linux.rb  for our VM boxes.

**Comment by DarshanMurthy** [comment]
It is solved now!



require 'chef/provisioning/vagrant_driver'

vagrant_box 'sles11sp3' do
  url 'https://jenkins-hzn.eng.vmware.com/tools/vagrant/sles11sp3.box'
end

with_driver 'vagrant'

# This works
with_machine_options :vagrant_config =>'     config.vm.synced_folder ".", "/vagrant", disabled: true
',
  :vagrant_options => {
    'vm.box' => 'sles11sp3',
    'vm.box_url' => 'http://jenkins-hzn.eng.vmware.com/tools/vagrant/sles11sp3.box',
    'vm.hostname' => 'default-sles11sp3.vagrantup.com'
}

**Comment by afiune** [comment]
Congrats!
